import React, { useMemo, useState } from 'react';
import {
  ActionSheetIOS,
  Alert,
  Linking,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Image } from 'expo-image';
import QRCode from 'react-native-qrcode-svg';
import { useAuth } from '@/hooks/AuthProvider';
import { useData } from '@/hooks/useData';
import { useGate } from '@/hooks/useGate';
import { colors, fonts, radius, spacing } from '@/theme';
import { fmtDate, fmtPetAge, daysUntil } from '@/utils/dates';
import { fmtWeight } from '@/utils/units';
import { SPECIES_LABEL, SPECIES_EMOJI } from '@/utils/petIcon';
import { canonicalizeVaccineName } from '@/utils/vaccineNames';
import type { Pet, VaccineRecord, Medication } from '@/types/models';

// Plain-text emergency card. Used by the share-via-text and email
// paths, and encoded as the payload of the QR code so any scanner
// (iPhone Camera, third-party QR app) can surface the info without
// requiring PawProof to be installed.
function buildEmergencyText(input: {
  pet: Pet;
  vaccines: VaccineRecord[];
  meds: Medication[];
  // Owner is the signed-in user. Surfaced as the first contact in
  // the shared text so whoever finds the pet knows who to call
  // first, before falling through to the emergency contact.
  ownerName: string | null;
  ownerEmail: string | null;
}): string {
  const { pet, vaccines, meds, ownerName, ownerEmail } = input;
  const lines: string[] = [];
  lines.push(`PawProof — Emergency card for ${pet.name}`);
  lines.push(
    [
      SPECIES_LABEL[pet.species],
      pet.breed,
      fmtPetAge(pet.birthday, pet.approxAgeMonths),
      pet.weightKg != null ? fmtWeight(pet.weightKg) : null,
    ]
      .filter(Boolean)
      .join(' · '),
  );
  lines.push('');

  if (ownerName || ownerEmail) {
    lines.push('OWNER');
    if (ownerName) lines.push(ownerName);
    if (ownerEmail) lines.push(ownerEmail);
    lines.push('');
  }
  if (pet.allergies) {
    lines.push('ALLERGIES');
    lines.push(pet.allergies);
    lines.push('');
  }
  if (pet.emergencyNotes) {
    lines.push('EMERGENCY NOTES');
    lines.push(pet.emergencyNotes);
    lines.push('');
  }
  // Care instructions: only include sections the user actually
  // filled in. A sitter glancing at the share text gets exactly the
  // notes that matter, with no empty headings.
  if (pet.feedingInstructions) {
    lines.push('FEEDING');
    lines.push(pet.feedingInstructions);
    lines.push('');
  }
  if (pet.walkRoutine) {
    lines.push('WALKS & EXERCISE');
    lines.push(pet.walkRoutine);
    lines.push('');
  }
  if (pet.behaviorNotes) {
    lines.push('BEHAVIOR NOTES');
    lines.push(pet.behaviorNotes);
    lines.push('');
  }
  if (pet.favoriteThings) {
    lines.push('FAVORITES');
    lines.push(pet.favoriteThings);
    lines.push('');
  }
  if (pet.boardingInstructions) {
    lines.push('BOARDING & SITTING');
    lines.push(pet.boardingInstructions);
    lines.push('');
  }
  if (pet.vetName || pet.vetPhone) {
    lines.push('VET');
    if (pet.vetName) lines.push(pet.vetName);
    if (pet.vetPhone) lines.push(pet.vetPhone);
    lines.push('');
  }
  if (pet.emergencyContactName || pet.emergencyContactPhone) {
    lines.push('EMERGENCY CONTACT');
    if (pet.emergencyContactName) lines.push(pet.emergencyContactName);
    if (pet.emergencyContactPhone) lines.push(pet.emergencyContactPhone);
    lines.push('');
  }
  if (pet.microchip || pet.insurance || pet.birthday) {
    lines.push('IDENTIFICATION');
    if (pet.birthday) lines.push(`DOB: ${fmtDate(pet.birthday)}`);
    if (pet.microchip) lines.push(`Microchip: ${pet.microchip}`);
    if (pet.insurance) lines.push(`Insurance: ${pet.insurance}`);
    lines.push('');
  }
  if (meds.length > 0) {
    lines.push('CURRENT MEDICATIONS');
    for (const m of meds) {
      const parts = [m.name, m.dosage, m.frequency, m.instructions].filter(Boolean);
      lines.push(`- ${parts.join(' · ')}`);
    }
    lines.push('');
  }
  if (vaccines.length > 0) {
    lines.push('RECENT VACCINES');
    for (const v of vaccines) {
      const exp = v.expirationDate ? ` (expires ${fmtDate(v.expirationDate)})` : '';
      lines.push(`- ${canonicalizeVaccineName(v.vaccineName)}: ${fmtDate(v.dateGiven)}${exp}`);
    }
    lines.push('');
  }
  lines.push('Generated by PawProof. Not a medical document.');
  return lines.join('\n');
}

/**
 * Pet emergency card. Designed to be readable at a glance by a vet, sitter,
 * or stranger. High-contrast, large type, tap-to-call buttons. Reads as a
 * physical "ID card" rather than a settings screen.
 */
export default function EmergencyCardScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { user, profile } = useAuth();
  const { pets, vaccines, medications } = useData();
  const { check, isPremium } = useGate();
  const [qrOpen, setQrOpen] = useState(false);

  const pet = pets.find(p => p.id === id);
  const activeMeds = useMemo(
    () => medications.filter(m => m.petId === id && m.isActive),
    [medications, id],
  );
  const recentVaccines = useMemo(
    () => vaccines
      .filter(v => v.petId === id)
      .sort((a, b) => +new Date(b.dateGiven) - +new Date(a.dateGiven))
      .slice(0, 5),
    [vaccines, id],
  );

  if (!pet) {
    return (
      <View style={styles.empty}>
        <Stack.Screen options={{ title: 'Emergency' }} />
        <Text>Pet not found.</Text>
      </View>
    );
  }

  const callVet = () => {
    if (pet.vetPhone) Linking.openURL(`tel:${pet.vetPhone.replace(/[^\d+]/g, '')}`);
  };
  const callEmergency = () => {
    if (pet.emergencyContactPhone) Linking.openURL(`tel:${pet.emergencyContactPhone.replace(/[^\d+]/g, '')}`);
  };

  // Share picker: text message (sms:), email (mailto:), or QR code.
  // The plain-text payload is identical across all three so the
  // recipient gets the same info regardless of channel.
  const ownerName = profile?.displayName ?? user?.displayName ?? null;
  const ownerEmail = profile?.email ?? user?.email ?? null;
  const emergencyText = useMemo(
    () =>
      buildEmergencyText({
        pet,
        vaccines: recentVaccines,
        meds: activeMeds,
        ownerName,
        ownerEmail,
      }),
    [pet, recentVaccines, activeMeds, ownerName, ownerEmail],
  );

  const shareViaText = () => {
    const body = encodeURIComponent(emergencyText);
    // iOS uses `&` after the empty number; Android uses `?`. Both
    // forms work on iOS, only the `?` form works on Android.
    const url = Platform.OS === 'ios' ? `sms:&body=${body}` : `sms:?body=${body}`;
    Linking.openURL(url).catch(() =>
      Alert.alert('Messages unavailable', 'Could not open the Messages app.'),
    );
  };

  const shareViaEmail = () => {
    const subject = encodeURIComponent(`${pet.name} — emergency info`);
    const body = encodeURIComponent(emergencyText);
    Linking.openURL(`mailto:?subject=${subject}&body=${body}`).catch(() =>
      Alert.alert('Email unavailable', 'No email app is set up on this device.'),
    );
  };

  const shareGeneric = () => {
    // System share sheet — covers AirDrop, Notes, third-party apps.
    Share.share({
      message: emergencyText,
      title: `${pet.name} — emergency info`,
    }).catch(() => {});
  };

  // PDF export of the emergency card is Plus-only. Free users get
  // text/email/QR (no Plus needed), so they can still share the info.
  // The PDF path runs the existing pet-health PDF generator with the
  // sitter-style layout and routes free users to the paywall via the
  // pdf_export gate. The gate's per-trigger copy is set in
  // premium.GATE_COPY.
  const exportAsPdf = () => {
    if (!check('pdf_export')) return;
    // When Plus: kick to the per-pet share/export route which already
    // hosts the PDF flow.
    router.push({ pathname: '/pet/[id]', params: { id: pet.id } });
  };

  const openShareMenu = () => {
    // Order matters: the cheapest, free paths go first; PDF (Plus) is
    // last and clearly labelled so users know it's a paid path.
    const pdfLabel = isPremium ? 'Export as PDF' : 'Export PDF (Plus)';
    const options = ['Text message', 'Email', 'Show QR code', pdfLabel, 'More…', 'Cancel'];
    if (Platform.OS === 'ios') {
      ActionSheetIOS.showActionSheetWithOptions(
        {
          title: `Share ${pet.name}'s emergency card`,
          options,
          cancelButtonIndex: options.length - 1,
        },
        idx => {
          if (idx === 0) shareViaText();
          else if (idx === 1) shareViaEmail();
          else if (idx === 2) setQrOpen(true);
          else if (idx === 3) exportAsPdf();
          else if (idx === 4) shareGeneric();
        },
      );
    } else {
      Alert.alert(`Share ${pet.name}'s emergency card`, undefined, [
        { text: 'Text message', onPress: shareViaText },
        { text: 'Email', onPress: shareViaEmail },
        { text: 'Show QR code', onPress: () => setQrOpen(true) },
        { text: pdfLabel, onPress: exportAsPdf },
        { text: 'More…', onPress: shareGeneric },
        { text: 'Cancel', style: 'cancel' },
      ]);
    }
  };

  return (
    <ScrollView style={{ flex: 1, backgroundColor: colors.bg }} contentContainerStyle={styles.scroll}>
      <Stack.Screen
        options={{
          title: 'Emergency Card',
          headerBackButtonDisplayMode: 'minimal',
          headerRight: () => (
            <Pressable onPress={openShareMenu} hitSlop={10} style={styles.headerShareBtn}>
              <Ionicons name="share-outline" size={22} color={colors.text} />
            </Pressable>
          ),
        }}
      />

      {/* Hero: big ID-card feel */}
      <View style={styles.hero}>
        {pet.photoUrl ? (
          <Image source={{ uri: pet.photoUrl }} style={styles.heroPhoto} contentFit="cover" />
        ) : (
          <View style={[styles.heroPhoto, styles.heroPhotoEmpty]}>
            <Text style={{ fontSize: 56 }}>{SPECIES_EMOJI[pet.species] ?? '🐾'}</Text>
          </View>
        )}
        <Text style={styles.heroName}>{pet.name}</Text>
        <Text style={styles.heroSub}>
          {SPECIES_LABEL[pet.species]}
          {pet.breed ? ` · ${pet.breed}` : ''}
          {fmtPetAge(pet.birthday, pet.approxAgeMonths) ? ` · ${fmtPetAge(pet.birthday, pet.approxAgeMonths)}` : ''}
        </Text>
        {pet.weightKg != null ? (
          <Text style={styles.heroSub}>{fmtWeight(pet.weightKg)}</Text>
        ) : null}
      </View>

      {/* Critical: allergies + emergency notes */}
      {pet.allergies ? (
        <Card tone="danger" icon="warning-outline" title="Allergies">
          <Text style={styles.criticalText}>{pet.allergies}</Text>
        </Card>
      ) : null}
      {pet.emergencyNotes ? (
        <Card tone="danger" icon="medical-outline" title="Emergency notes">
          <Text style={styles.criticalText}>{pet.emergencyNotes}</Text>
        </Card>
      ) : null}

      {/* Owner — first line of contact for whoever found the pet.
          Always rendered; if displayName is missing we still show
          the email so there's a way to reach the user. */}
      {(ownerName || ownerEmail) ? (
        <Card tone="primary" icon="happy-outline" title="Owner">
          {ownerName ? <Text style={styles.contactName}>{ownerName}</Text> : null}
          {ownerEmail ? (
            <Text style={{ fontSize: 14, color: colors.textMuted }}>{ownerEmail}</Text>
          ) : null}
        </Card>
      ) : null}

      {/* Tap-to-call contacts */}
      <Card tone="primary" icon="call-outline" title="Vet">
        {pet.vetName ? <Text style={styles.contactName}>{pet.vetName}</Text> : null}
        {pet.vetPhone ? (
          <Pressable onPress={callVet} style={({ pressed }) => [styles.callBtn, pressed && { opacity: 0.85 }]}>
            <Ionicons name="call" size={16} color="#fff" />
            <Text style={styles.callBtnText}>{pet.vetPhone}</Text>
          </Pressable>
        ) : (
          <View style={{ gap: 6, alignItems: 'flex-start' }}>
            <Text style={styles.muted}>No vet phone added</Text>
            <Pressable
              onPress={() => router.push({ pathname: '/pet/edit/[id]', params: { id: pet.id } })}
              hitSlop={6}
              style={({ pressed }) => [styles.editLink, pressed && { opacity: 0.85 }]}
            >
              <Ionicons name="add-circle-outline" size={14} color={colors.primary} />
              <Text style={styles.editLinkText}>Add vet phone</Text>
            </Pressable>
          </View>
        )}
      </Card>

      {(pet.emergencyContactName || pet.emergencyContactPhone) ? (
        <Card tone="primary" icon="person-outline" title="Emergency contact">
          {pet.emergencyContactName ? <Text style={styles.contactName}>{pet.emergencyContactName}</Text> : null}
          {pet.emergencyContactPhone ? (
            <Pressable onPress={callEmergency} style={({ pressed }) => [styles.callBtn, pressed && { opacity: 0.85 }]}>
              <Ionicons name="call" size={16} color="#fff" />
              <Text style={styles.callBtnText}>{pet.emergencyContactPhone}</Text>
            </Pressable>
          ) : null}
        </Card>
      ) : null}

      {/* IDs */}
      <Card tone="muted" icon="finger-print-outline" title="Identification">
        <InfoRow label="Date of birth" value={pet.birthday ? fmtDate(pet.birthday) : 'Unknown'} />
        <InfoRow label="Microchip" value={pet.microchip || 'Not registered'} />
        <InfoRow label="Insurance" value={pet.insurance || 'None'} />
      </Card>

      {/* Active medications */}
      {activeMeds.length > 0 ? (
        <Card tone="muted" icon="medkit-outline" title="Current medications">
          {activeMeds.map(m => (
            <View key={m.id} style={styles.medLine}>
              <Text style={styles.medName}>{m.name}</Text>
              <Text style={styles.medMeta}>
                {m.dosage ? `${m.dosage} · ` : ''}{frequencyShort(m.frequency)}
                {m.instructions ? ` · ${m.instructions}` : ''}
              </Text>
            </View>
          ))}
        </Card>
      ) : null}

      {/* Recent vaccinations. Date labels are explicit ("Current
          until", "Expired", "Given") because a vet or sitter reading
          the card under stress shouldn't have to guess whether a bare
          date is the given or expiration date. */}
      {recentVaccines.length > 0 ? (
        <Card tone="muted" icon="shield-checkmark-outline" title="Vaccine status">
          {recentVaccines.map(v => {
            const days = v.expirationDate ? daysUntil(v.expirationDate) : null;
            const isExpired = days != null && days < 0;
            const isExpiringSoon = days != null && days >= 0 && days <= 30;
            let label = '';
            if (v.expirationDate) {
              if (isExpired) label = `Expired ${fmtDate(v.expirationDate)}`;
              else if (isExpiringSoon) label = `Expires in ${days}d · ${fmtDate(v.expirationDate)}`;
              else label = `Current until ${fmtDate(v.expirationDate)}`;
            } else {
              label = `Given ${fmtDate(v.dateGiven)}`;
            }
            return (
              <View key={v.id} style={styles.vaccLine}>
                <Text style={styles.vaccName}>{canonicalizeVaccineName(v.vaccineName)}</Text>
                <Text
                  style={[
                    styles.vaccStatus,
                    isExpired && { color: colors.danger, fontWeight: '700' },
                    isExpiringSoon && { color: '#92400e', fontWeight: '700' },
                  ]}
                >
                  {label}
                </Text>
              </View>
            );
          })}
        </Card>
      ) : null}

      <Text style={styles.footer}>Generated by PawProof · Not a medical document</Text>

      {/* QR code overlay. Encodes the same plain-text payload as the
          text/email paths so any scanner can surface the info — no
          PawProof account required to read. */}
      <Modal animationType="fade" transparent visible={qrOpen} onRequestClose={() => setQrOpen(false)}>
        <Pressable onPress={() => setQrOpen(false)} style={styles.qrBackdrop}>
          <Pressable onPress={() => {}} style={styles.qrSheet}>
            <View style={styles.qrHeader}>
              <View>
                <Text style={styles.qrTitle}>{pet.name}'s emergency info</Text>
                <Text style={styles.qrSubtitle}>
                  Point your camera at the code to read allergies, vet contacts,
                  and active medications.
                </Text>
              </View>
              <Pressable onPress={() => setQrOpen(false)} hitSlop={10} style={styles.qrClose}>
                <Ionicons name="close" size={20} color={colors.text} />
              </Pressable>
            </View>
            <View style={styles.qrFrame}>
              <QRCode
                value={emergencyText.slice(0, 1500)}
                size={240}
                backgroundColor="#ffffff"
                color="#0e1a20"
              />
            </View>
            <Text style={styles.qrFootnote}>
              Older scanners may truncate long codes. Use Text or Email for the
              full record.
            </Text>
            <Pressable
              onPress={() => {
                setQrOpen(false);
                shareGeneric();
              }}
              style={({ pressed }) => [styles.qrShareBtn, pressed && { opacity: 0.88 }]}
            >
              <Ionicons name="share-outline" size={16} color="#fff" />
              <Text style={styles.qrShareBtnText}>Share the text instead</Text>
            </Pressable>
          </Pressable>
        </Pressable>
      </Modal>
    </ScrollView>
  );
}

function Card({ tone, icon, title, children }: {
  tone: 'danger' | 'primary' | 'muted';
  icon: keyof typeof Ionicons.glyphMap;
  title: string;
  children: React.ReactNode;
}) {
  const styleByTone = tone === 'danger' ? cardTones.danger : tone === 'primary' ? cardTones.primary : cardTones.muted;
  return (
    <View style={[styles.card, { backgroundColor: styleByTone.bg, borderColor: styleByTone.border }]}>
      <View style={styles.cardHeader}>
        <View style={[styles.cardIcon, { backgroundColor: styleByTone.iconBg }]}>
          <Ionicons name={icon} size={16} color={styleByTone.iconColor} />
        </View>
        <Text style={[styles.cardTitle, { color: styleByTone.titleColor }]}>{title}</Text>
      </View>
      <View style={{ gap: 6 }}>{children}</View>
    </View>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.infoRow}>
      <Text style={styles.infoLabel}>{label}</Text>
      <Text style={styles.infoValue}>{value}</Text>
    </View>
  );
}

function frequencyShort(f: string): string {
  const map: Record<string, string> = {
    once_daily: '1x daily', twice_daily: '2x daily', three_times_daily: '3x daily',
    every_other_day: 'every 2 days', weekly: 'weekly', monthly: 'monthly', as_needed: 'as needed',
  };
  return map[f] ?? f;
}

const cardTones = {
  danger:  { bg: colors.dangerSoft,  border: colors.danger + '40',  iconBg: '#fbd5d5', iconColor: '#991b1b', titleColor: '#991b1b' },
  primary: { bg: colors.primarySoft, border: colors.primary + '40', iconBg: '#cfe9ef', iconColor: colors.primaryDark, titleColor: colors.primaryDark },
  muted:   { bg: colors.card,        border: colors.border,         iconBg: colors.cardSubtle, iconColor: colors.textMuted, titleColor: colors.textMuted },
};

const styles = StyleSheet.create({
  scroll: { padding: spacing.base, paddingBottom: spacing['3xl'], gap: spacing.md },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.bg },

  hero: { alignItems: 'center', gap: 4, paddingVertical: spacing.lg },
  heroPhoto: { width: 140, height: 140, borderRadius: 32, backgroundColor: colors.primarySoft },
  heroPhotoEmpty: { alignItems: 'center', justifyContent: 'center' },
  heroName: { fontSize: 32, fontWeight: '800', color: colors.text, marginTop: spacing.sm, letterSpacing: -0.5 },
  heroSub: { fontSize: 15, color: colors.textMuted },

  card: { padding: spacing.md, borderRadius: radius.lg, gap: spacing.sm, borderWidth: 1 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  cardIcon: { width: 28, height: 28, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  cardTitle: { fontSize: 12, fontWeight: '700', letterSpacing: 0.5, textTransform: 'uppercase' },

  criticalText: { fontSize: 17, color: colors.text, fontWeight: '600', lineHeight: 22 },

  contactName: { fontSize: 16, fontWeight: '600', color: colors.text },
  callBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    backgroundColor: colors.primary,
    paddingVertical: 12, paddingHorizontal: spacing.base,
    borderRadius: radius.md,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  callBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },

  infoRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  infoLabel: { fontSize: 13, color: colors.textMuted, fontWeight: '600' },
  infoValue: { fontSize: 14, color: colors.text, flexShrink: 1, textAlign: 'right' },

  medLine: { paddingVertical: 4 },
  medName: { fontSize: 14, fontWeight: '600', color: colors.text },
  medMeta: { fontSize: 12, color: colors.textMuted },

  vaccLine: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  vaccName: { fontSize: 14, fontWeight: '600', color: colors.text },
  vaccStatus: { fontSize: 12, color: colors.textMuted },

  muted: { fontSize: 13, color: colors.textMuted, fontStyle: 'italic' },
  editLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.primarySoft,
  },
  editLinkText: { fontSize: 12, color: colors.primary, fontWeight: '700' },
  footer: { fontSize: 11, color: colors.textFaint, textAlign: 'center', marginTop: spacing.md },

  headerShareBtn: {
    width: 36, height: 36, borderRadius: 18,
    alignItems: 'center', justifyContent: 'center',
    marginRight: 4,
  },

  // QR overlay
  qrBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  qrSheet: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: colors.bg,
    borderRadius: radius.xl,
    padding: spacing.lg,
    gap: spacing.md,
  },
  qrHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  qrTitle: { fontSize: 16, fontFamily: fonts.display.bold, color: colors.text },
  qrSubtitle: { fontSize: 12, color: colors.textMuted, marginTop: 4, lineHeight: 17, paddingRight: 24 },
  qrClose: {
    position: 'absolute',
    top: -4, right: -4,
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: colors.cardSubtle,
    alignItems: 'center', justifyContent: 'center',
  },
  qrFrame: {
    alignSelf: 'center',
    padding: spacing.md,
    backgroundColor: '#fff',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  qrFootnote: { fontSize: 11, color: colors.textFaint, textAlign: 'center', lineHeight: 16 },
  qrShareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
  },
  qrShareBtnText: { fontSize: 13, fontFamily: fonts.body.semibold, color: '#fff' },
});
